[package]
name = "amino"
version = "0.1.0"
authors = ["zaki", "Ismail Khoffi <ismail@tendermint.com"]


[dependencies]
amino-derive = { path = "amino-derive" }
byteorder = "1"
bytes = "0.4"
chrono = "0.4.2"
sha2 = "0.7"
