version: 2

jobs:
  build:
    docker:
      - image: iqlusion/rust-ci:20180913.2 # bump cache keys when modifying this
    environment:
    steps:
      - checkout
      - restore_cache:
          key: cache-201804050 # bump save_cache key below too
      - run:
          name: build (nightly, all features)
          command: |
            rustc --version --verbose
            cargo --version --verbose
            cargo build --features=$CARGO_FEATURES
      - run:
          name: test (nightly, all features)
          command: |
            rustc --version --verbose
            cargo --version --verbose
            cargo test --features=$CARGO_FEATURES
      - save_cache:
          key: cache-20180913.2 # bump restore_cache key above too
          paths:
            - "~/.cargo"
            - "./target"